---
- name: Install Weka CSI Plugin
  hosts: control_plane[0]
  gather_facts: no

  vars:
    weka_namespace: "csi-wekafs"
    secret_name: "csi-wekafs-api-secret"
    storage_class_name: "storageclass-wekafs-dir-api"

  tasks:
    - name: Add Helm repository for Weka CSI Plugin
      shell: helm repo add csi-wekafs https://weka.github.io/csi-wekafs
      register: helm_repo_add
      changed_when: "'already exists' not in helm_repo_add.stdout"

    - name: Install Weka CSI Plugin via Helm
      shell: |
        helm install csi-wekafs csi-wekafs/csi-wekafsplugin \
        --namespace {{ weka_namespace }} --create-namespace
      args:
        creates: "/tmp/csi-wekafs-installed"

    - name: Base64 encode username, password, and endpoints
      set_fact:
        encoded_username: "{{ weka_username | b64encode }}"
        encoded_password: "{{ weka_password | b64encode }}"
        encoded_endpoints: "{{ weka_endpoints | b64encode }}"

    - name: Generate CSI WekaFS API Secret YAML from template
      template:
        src: templates/csi-wekafs-api-secret.yaml.j2
        dest: /tmp/csi-wekafs-api-secret.yaml

    - name: Apply CSI WekaFS API Secret
      shell: kubectl apply -f /tmp/csi-wekafs-api-secret.yaml

    - name: Generate Storage Class YAML from template
      template:
        src: templates/storageclass-wekafs-dir-api.yaml.j2
        dest: /tmp/storageclass-wekafs-dir-api.yaml

    - name: Apply Storage Class
      shell: kubectl apply -f /tmp/storageclass-wekafs-dir-api.yaml

    - name: Verify Storage Class
      shell: kubectl get sc
      register: sc_output

    - debug:
        msg: "{{ sc_output.stdout }}"

